layout_spectrum: 0.3531252215616405
typography_spectrum: 0.9013795002829283
color:
  brandStrength: 0.7475379796233028
  lightness: 0.17919221660122275
  saturation: 0.8924645595252514
  rhythmicContrast: 0.03196456003934145
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
name: Bowie Croisant
navigation:
  - name: Bowie Croisant Portfolio Site
    url: bowiecroisant.com
    type: external
  - name: Bowie Croisant Wordpress >2013
    url: 'https://bowiecroisant.wordpress.com/'
    type: external
